DROP USER ETPBY_FA CASCADE;
CREATE USER ETPBY_FA IDENTIFIED BY pby
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER ETPBY_FA QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO ETPBY_FA;
GRANT "RESOURCE" TO ETPBY_FA;
ALTER USER ETPBY_FA DEFAULT ROLE "CONNECT","RESOURCE";  